table salesorderdetail
	lineageTag: 3f364c44-a882-4a68-9c97-9859bccfb09c
	sourceLineageTag: [dbo].[salesorderdetail]

	measure TotalQty = sum(salesorderdetail[OrderQty])
		formatString: 0
		lineageTag: 207cb28f-693b-46a0-b336-02cfd82b24d4

		changedProperty = Name

	column SalesOrderID
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: 63ce4f41-b71a-436e-b51e-ca16856aace8
		sourceLineageTag: SalesOrderID
		summarizeBy: count
		sourceColumn: SalesOrderID

		annotation SummarizationSetBy = Automatic

	column SalesOrderDetailID
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: cc658596-433a-4f35-951a-731ff99a2179
		sourceLineageTag: SalesOrderDetailID
		summarizeBy: count
		sourceColumn: SalesOrderDetailID

		annotation SummarizationSetBy = Automatic

	column OrderQty
		dataType: int64
		formatString: 0
		sourceProviderType: smallint
		lineageTag: 47c0b6a2-94d4-4946-a263-8b4469b44968
		sourceLineageTag: OrderQty
		summarizeBy: sum
		sourceColumn: OrderQty

		annotation SummarizationSetBy = Automatic

	column ProductID
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: 98ca284d-6d50-421c-8c34-978267600186
		sourceLineageTag: ProductID
		summarizeBy: count
		sourceColumn: ProductID

		annotation SummarizationSetBy = Automatic

	column UnitPrice
		dataType: double
		sourceProviderType: decimal(19, 4)
		lineageTag: d85e6f9d-fe93-4301-a323-f151912c5e6e
		sourceLineageTag: UnitPrice
		summarizeBy: sum
		sourceColumn: UnitPrice

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column UnitPriceDiscount
		dataType: double
		sourceProviderType: decimal(19, 4)
		lineageTag: 26480bf6-26b9-4f14-89f2-7130ec031386
		sourceLineageTag: UnitPriceDiscount
		summarizeBy: sum
		sourceColumn: UnitPriceDiscount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column LineTotal
		dataType: int64
		formatString: 0
		sourceProviderType: decimal(18, 0)
		lineageTag: 4317556f-d32a-402f-bf44-81a4604c10d2
		sourceLineageTag: LineTotal
		summarizeBy: sum
		sourceColumn: LineTotal

		annotation SummarizationSetBy = Automatic

	column rowguid
		dataType: string
		sourceProviderType: char
		lineageTag: 4fd4ef54-f3df-4b81-a3c4-bd498970f0a5
		sourceLineageTag: rowguid
		summarizeBy: none
		sourceColumn: rowguid

		annotation SummarizationSetBy = Automatic

	column ModifiedDate
		dataType: dateTime
		formatString: General Date
		sourceProviderType: datetime2
		lineageTag: 6e74a353-68b8-44fe-a752-28bb842460da
		sourceLineageTag: ModifiedDate
		summarizeBy: none
		sourceColumn: ModifiedDate

		annotation SummarizationSetBy = Automatic

	partition salesorderdetail = entity
		mode: directLake
		source
			entityName: salesorderdetail
			schemaName: dbo
			expressionSource: DatabaseQuery

	annotation PBI_ResultType = Table

